import { Product } from "./types/product";

export const categories = [
  {
    id: "electronics",
    name: "Electronics",
    image: "/products/samsung.webp",
    count: 4,
  },
  {
    id: "sports",
    name: "Sports",
    image: "/products/skateboard.webp",
    count: 2,
  },
  {
    id: "fashion",
    name: "Fashion",
    image: "/products/jersey.webp",
    count: 2,
  },
  {
    id: "vehicles",
    name: "Vehicles",
    image: "/products/car.webp",
    count: 1,
  },
  {
    id: "gaming",
    name: "Gaming & Media",
    image: "/products/ps5.webp",
    count: 1,
  },
  {
    id: "home",
    name: "Home",
    image: "/products/kettle.webp",
    count: 4,
  },
];

export const priceDistributionData = [
  { range: "0-1k", count: 2 },
  { range: "1k-5k", count: 5 },
  { range: "5k-10k", count: 3 },
  { range: "10k-20k", count: 2 },
  { range: "20k-50k+", count: 2 },
];

export const conditionOptions = [
  { id: "new", label: "New" },
  { id: "used-like-new", label: "Used - Like New" },
  { id: "used-good", label: "Used - Good" },
  { id: "used-fair", label: "Used - Fair" },
  { id: "for-parts", label: "For Parts or Not Working" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Vintage Leather Sofa",
    description:
      "Beautiful vintage leather sofa in excellent condition. Perfect for any living room.",
    price: 4500,
    image: "/products/vintage-sofa.webp",
    seller: "FurnitureFinds",
    category: "Home",
    condition: "used-like-new",
    location: "Cape Town",
    createdAt: "2023-12-15T10:30:00Z",
    originalPrice: 8000,
    stock: 5,
    brand: "VintageCo",
    reviews: [
      {
        id: "1",
        user: "Alice",
        rating: 5,
        comment: "Absolutely love this sofa! It's so comfortable and stylish.",
        date: "2024-01-10",
      },
      {
        id: "2",
        user: "Bob",
        rating: 4,
        comment:
          "Great quality, but the color is slightly darker than in the pictures.",
        date: "2024-01-12",
      },
    ],
  },
  {
    id: "2",
    name: "Samsung Galaxy S22",
    description:
      "Samsung Galaxy S22 in perfect condition. Includes charger and original box.",
    price: 8999,
    image: "/products/samsung.webp",
    seller: "TechTraders",
    category: "Electronics",
    condition: "used-good",
    location: "Johannesburg",
    createdAt: "2024-01-20T14:45:00Z",
    originalPrice: 12000,
    stock: 10,
    brand: "Samsung",
    model: "S22",
    reviews: [
      {
        id: "1",
        user: "Charlie",
        rating: 5,
        comment: "Great phone! Fast and reliable. Highly recommend.",
        date: "2024-01-25",
      },
      {
        id: "2",
        user: "Diana",
        rating: 4,
        comment:
          "Good phone, but the battery life could be better. Overall satisfied.",
        date: "2024-01-28",
      },
    ],
  },
  {
    id: "3",
    name: "Mountain Bike - Trek",
    description:
      "Trek mountain bike with front suspension. Great for trails and city riding.",
    price: 6500,
    image: "/products/bicycle.webp",
    seller: "OutdoorGear",
    category: "Sports",
    condition: "used-fair",
    location: "Durban",
    createdAt: "2024-02-05T09:15:00Z",
    originalPrice: 9000,
    stock: 3,
    brand: "Trek",
    model: "X-Caliber 8",
    reviews: [
      {
        id: "1",
        user: "Ethan",
        rating: 4,
        comment: "Good bike for the price. A bit heavy but rides well.",
        date: "2024-02-10",
      },
      {
        id: "2",
        user: "Fiona",
        rating: 3,
        comment:
          "Decent bike, but had to replace the tires after a month. Not the best quality.",
        date: "2024-02-12",
      },
    ],
  },
  {
    id: "4",
    name: "Handmade Ceramic Vase",
    description:
      "Beautiful handmade ceramic vase. Perfect for flowers or as a decorative piece.",
    price: 350,
    image: "/products/vase.webp",
    seller: "ArtisanCrafts",
    category: "Home",
    condition: "new",
    location: "Pretoria",
    createdAt: "2024-03-10T16:20:00Z",
    stock: 20,
    brand: "Artisan",
  },
  {
    id: "5",
    name: "Vintage Vinyl Records Collection",
    description:
      "Collection of 20 vintage vinyl records from the 70s and 80s. Various artists.",
    price: 1200,
    image: "/products/vinyl.webp",
    seller: "MusicMasters",
    category: "Electronics",
    condition: "used-good",
    location: "Port Elizabeth",
    createdAt: "2024-04-01T11:30:00Z",
    originalPrice: 2000,
    stock: 8,
    brand: "Various",
    reviews: [
      {
        id: "1",
        user: "Jack",
        rating: 5,
        comment: "Great collection! Love the classic hits.",
        date: "2024-04-05",
      },
      {
        id: "2",
        user: "Kathy",
        rating: 4,
        comment:
          "Good condition, but a few records have scratches. Still a great buy.",
        date: "2024-04-08",
      },
    ],
  },
  {
    id: "6",
    name: "Professional DSLR Camera",
    description:
      "Canon EOS 5D Mark IV with 24-70mm lens. Perfect for professional photography.",
    price: 15000,
    image: "/products/camera.webp",
    seller: "PhotoPro",
    category: "Electronics",
    condition: "used-like-new",
    location: "Bloemfontein",
    createdAt: "2024-04-15T13:45:00Z",
    originalPrice: 25000,
    stock: 2,
    brand: "Canon",
    model: "EOS 5D Mark IV",
    reviews: [
      {
        id: "1",
        user: "Liam",
        rating: 5,
        comment:
          "Amazing camera! The image quality is stunning. Highly recommend for professionals.",
        date: "2024-04-20",
      },
      {
        id: "2",
        user: "Mia",
        rating: 4,
        comment:
          "Great camera, but the battery life could be better. Overall very satisfied.",
        date: "2024-04-22",
      },
    ],
  },
  {
    id: "7",
    name: "Broken iPhone 12 for Parts",
    description:
      "iPhone 12 with cracked screen and battery issues. Good for parts or repair.",
    price: 2500,
    image: "/products/broken-iphone.webp",
    seller: "PhoneRepair",
    category: "Electronics",
    condition: "for-parts",
    location: "Johannesburg",
    createdAt: "2024-02-18T09:30:00Z",
    originalPrice: 12000,
    stock: 1,
    brand: "Apple",
    model: "iPhone 12",
    reviews: [
      {
        id: "1",
        user: "Nina",
        rating: 3,
        comment:
          "Good for parts, but I expected more. The battery was completely dead.",
        date: "2024-02-20",
      },
      {
        id: "2",
        user: "Oscar",
        rating: 2,
        comment:
          "Not worth it. The screen was more damaged than described. Disappointed.",
        date: "2024-02-22",
      },
    ],
  },
  {
    id: "8",
    name: "Brand New PlayStation 5",
    description:
      "Sealed PlayStation 5 Disc Edition. Never opened, with full warranty.",
    price: 13999,
    image: "/products/ps5.webp",
    seller: "GameZone",
    category: "Gaming",
    condition: "new",
    location: "Cape Town",
    createdAt: "2024-04-20T15:45:00Z",
    stock: 10,
    brand: "Sony",
    model: "PlayStation 5",
  },
  {
    id: "9",
    name: "Antique Wooden Desk",
    description:
      "Beautiful antique wooden desk from the 1920s. Some wear but in good condition.",
    price: 7500,
    image: "/products/desk.webp",
    seller: "VintageFinds",
    category: "Home",
    condition: "used-good",
    location: "Durban",
    createdAt: "2024-03-05T11:20:00Z",
    originalPrice: 12000,
    stock: 1,
    brand: "AntiqueCo",
    reviews: [
      {
        id: "1",
        user: "Rachel",
        rating: 5,
        comment:
          "Absolutely love this desk! It's a perfect addition to my home office.",
        date: "2024-03-10",
      },
    ],
  },
  {
    id: "10",
    name: "Designer Handbag",
    description:
      "Authentic designer handbag, barely used. Comes with dust bag and authenticity card.",
    price: 25000,
    image: "/products/handbag.webp",
    seller: "LuxuryItems",
    category: "Fashion",
    condition: "used-like-new",
    location: "Sandton",
    createdAt: "2024-04-10T14:15:00Z",
    originalPrice: 40000,
    stock: 3,
    brand: "Gucci",
    reviews: [
      {
        id: "1",
        user: "Sophia",
        rating: 5,
        comment:
          "Gorgeous handbag! The quality is amazing and it looks brand new.",
        date: "2024-04-15",
      },
      {
        id: "2",
        user: "Tom",
        rating: 4,
        comment:
          "Very stylish and practical. A bit pricey, but worth it for the brand.",
        date: "2024-04-18",
      },
    ],
  },
  {
    id: "11",
    name: "Toyota Corolla",
    description:
      "2018 Toyota Corolla, 50,000 km, full service history. Excellent condition.",
    price: 85000,
    image: "/products/car.webp",
    seller: "CarDeals",
    category: "Vehicles",
    condition: "used-good",
    location: "Cape Town",
    createdAt: "2024-04-25T10:00:00Z",
    originalPrice: 150000,
    stock: 1,
    brand: "Toyota",
    model: "Corolla",
    reviews: [
      {
        id: "1",
        user: "Uma",
        rating: 5,
        comment:
          "Great car! Very reliable and fuel-efficient. Highly recommend.",
        date: "2024-04-30",
      },
    ],
  },
  {
    id: "12",
    name: "KickFlip Quarter Zip Jersey",
    description:
      "Stylish quarter zip jersey from KickFlip. Perfect for casual wear.",
    price: 500,
    image: "/products/jersey.webp",
    seller: "FashionHub",
    category: "Fashion",
    condition: "new",
    location: "Johannesburg",
    createdAt: "2024-04-30T12:30:00Z",
    brand: "KickFlip",
    stock: 15,
  },
  {
    id: "13",
    name: "Smeg Kettle",
    description: "Stylish Smeg kettle in pastel blue. Perfect for any kitchen.",
    price: 1500,
    image: "/products/kettle.webp",
    seller: "HomeEssentials",
    category: "Home",
    condition: "new",
    location: "Pretoria",
    createdAt: "2024-05-01T09:00:00Z",
    brand: "Smeg",
    stock: 25,
  },
  {
    id: "14",
    name: "Skateboard",
    description:
      "High-quality skateboard with custom design. Perfect for tricks and cruising.",
    price: 1200,
    image: "/products/skateboard.webp",
    seller: "SkateShop",
    category: "Sports",
    condition: "new",
    location: "Durban",
    createdAt: "2024-05-02T11:00:00Z",
    brand: "SkateCo",
    stock: 30,
  },
];
